### ISSUE TITLE
Setup instructions doesn't include copy ssh keys to the server's authorized key.

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#16]
Following command may help:
`cat ~/.ssh/id_rsa.pub | ssh zeronone@192.168.4.2 "cat >> ~/.ssh/authorized_keys"`
OR
`cat ~/.ssh/id_rsa.pub | ssh zeronone@192.168.4.2 "mkdir ~/.ssh; cat >> ~/.ssh/authorized_keys"`

**Comment by cacyss0807** [comment]
Yes, but I think that this should be done explicitly by whom ever sets up the RBpi because the server IP might change (specially in the testing face). 

Probably we can add an explanation on how to do it using the commands you mention or just `ssh-copy-id`; which also gets the job done.

Other way, that seems to be better and more use friendly, is to prompt the user with the server information, or reading this information from the `coe_client.conf` file.
